### ISSUE TITLE
Add darkmode

### ISSUE THREAD

**Issue by fumikito** [fumikito/kyom#38]
https://qiita.com/hmmrjn/items/131916f9f4257342b2f2

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: #fff;
  }
}
```
